### ISSUE TITLE
wrong image url generated

### ISSUE THREAD

**Issue by wuestkamp** [Bukashk0zzz/LiipImagineSerializationBundle#4]
```
/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 * @Vich\Uploadable
 * @Bukashk0zzz\LiipImagineSerializableClass
 */
class User extends BaseUser
{
    /**
     * @Assert\Image(minWidth=300, mimeTypes={"image/gif", "image/jpeg", "image/png"})
     * @Vich\UploadableField(mapping="member_image", fileNameProperty="photoName")
     */
    public $photo;

    /**
     * @ORM\Column(name="photo_name", nullable=true)
     * @Bukashk0zzz\LiipImagineSerializableField(filter={"member_small"}, virtualField="photoJs")
     */
    protected $photoName;
```

I am JMS-exposing fields using Yml file.

What gets serialized:

```
"photo": {
"member_small": http://app.local/app_dev.php/media/cache/resolve/member_small/579523e66cb25.png »
} ,
```

The correct url should be: http://app.local/app_dev.php/media/cache/resolve/member_small/media/members/579523e66cb25.png

Thanks

**Comment by kimwue** [comment]
```
liip_imagine:
    cache: default
    resolvers:
       default:
          web_path:
            web_root: %kernel.root_dir%/../web
            cache_prefix: /media/cache
```

**Comment by kimwue** [comment]
Looks like this was misconfiguration for my liip_imagine resolver!

**Comment by wuestkamp** [comment]
Hmm there still seems to be an issue:

http://app.local/app_dev.php/media/cache/resolve/member_small/579523e66cb25.png // wrong
http://app.local/app_dev.php/media/cache/resolve/member_small/media/members/579523e66cb25.png // should be like this

So it seems the media/members is missing in the url?

```
vich_uploader:
    db_driver: orm
    storage: gaufrette
    mappings:
        member_image:
            uri_prefix: /media/members
            upload_destination: member_image_fs
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid
```
